### ISSUE TITLE
after migration to angular 6 postcss-loader fails 

### ISSUE THREAD

**Issue by sancelot** [postcss/postcss-loader#393]
After migrating my application from angular 4 to 6 , I have got some related mistake messages issued by postcss-loader 

### Details

the src/styles.css contains only:
/* You can add global styles to this file, and also import other style files */

### Error (Logs|Stacks)
`<details>{{
ERROR in ./src/app/outilsvg/forms.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/styles.css (./node_modules/raw-loader!./node_modules/postcss-loader??embedded!./src/styles.css)
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/cube/cube.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/outilsvg/outilsvg.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/outilsvg/paneloutil.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/app.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/outilsvg/zigzagview.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/mouvementview/mouvementview.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/mouvementview/svgslider/svgslider.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./src/app/language-picker/language-picker.component.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/flag-icon-css/css/flag-icon.css
Module build failed (from ./node_modules/postcss-loader/index.js):
TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /home/sancelot/NODEJS/PROJET2/PROJVIDE/node_modules/postcss-loader/index.js:122:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ℹ ｢wdm｣: Failed to compile.}}
</details>
`

### Reproduction (Code)
launching ng build it fails

```bash
$ ng build
```

### Environment

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|[linux][4.4.88]|[8.11.2]|6.4.1|3.0.0|

**Comment by evilebottnawi** [comment]
@sancelot better create this issue in `angular-cli` (`ng`)

**Comment by sancelot** [comment]
fixed : npm outdated pointed me that I was using 1.3.0 instead of 3.0.0
